name: p1-twojobs
on: [pull_request]
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo a
  b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo b
