name: p3-python
on: [pull_request]
jobs:
  p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -V
        working-directory: adapters/pdf
